frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\UploadForm;
use yii\web\UploadedFile;
use common\models\MasterData;
use common\models\MasterDataSearch;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'data', 'search', 'putway', 'putway_confirmation', 'index', 'shipment'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'data', 'search', 'putway','putway_confirmation', 'index', 'shipment'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        //return $this->goHome();
        return $this->redirect(['/site/login']);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionUpload()
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {
            $model->file = UploadedFile::getInstance($model, 'file');

            if ($model->validate()) {
                $model->file->saveAs('uploads/'. $model->file->baseName.'.'.$model->file->extension);
            }
        }
        return $this->render('upload', [
            'model' => $model,
        ]);
    }

    public function actionSearch()
    {
        $searchModel = new \common\models\MasterDataSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new \common\models\MasterData();

        return $this->render('search', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
    }

    public function actionSend($hu_number)
    {
        $model = \common\models\MasterData::find()->where(['hu_number' => $hu_number])->one();
        $count = \common\models\MasterData::find()->where(['status' => 'scan'])->count();
        $status = 'scan';
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Sukses Kirim data');

            return $this->redirect(['/site/search']);
        } else {
            return $this->render('create', [
                    'model' => $model,
                    $model->status = $status,
                ]);
        }
    }

    public function actionData()
    {
        $data = \common\models\MasterData::find()->where(['status' => 'scan']);
        $countQuery = clone $data;
        $pages = new \yii\data\Pagination(['totalCount' => $countQuery->count()]);
        $models = $data->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        
        if (isset($_POST['checkbox'])) {
            $status = 'confirm';
            //$no_pol = Yii::$app->request->post('no_pol');
            //$nama_supir = Yii::$app->request->post('driver_name');
            $no_sto = Yii::$app->request->post('no_sto');
            foreach ($_POST['checkbox'] as $index => $checkbox) {
                $check = ($checkbox);
                $update = "UPDATE master_data SET status='$status', no_sto='$no_sto' WHERE id='$check' ";

                $query = Yii::$app->db->createCommand($update)->execute();
            }
            if ($query) {
                $modelSto = new \common\models\MasterSto();
                $modelSto->no_sto = $no_sto;
                $modelSto->save();
            }
            $this->redirect(['/site/data']);
        }
        return $this->render('data', [
                'models' => $models,
                'pages' => $pages,
            ]);
    }
    public function actionPutway()
    {   
        $model = new \common\models\TabelPutway();

        if ($model->load(Yii::$app->request->post())) {
            $status = 'scan';
            $model->status = $status;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Sukses Putway');
                return $this->redirect(['/site/putway']);
            }
        } else {
            return $this->render('@backend/views/tabel-putway/create', [
                'model' => $model,
            ]);
        }
    }

    public function actionPutway_confirmation()
    {
        $models = \common\models\TabelPutway::find()->where(['status' => 'scan'])->all();
        //$count = clone $data;
        //$pages = new \yii\data\Pagination(['totalCount' => $count->count()]);
        //$models = $data->offset($pages->offset)
          //  ->limit($pages->limit)
            //->all();

        if (isset($_POST['checkbox'])) {
            $status = 'done';
            $refrence = Yii::$app->request->post('refrence');
            foreach ($_POST['checkbox'] as $key => $checkbox) {
                $check = ($checkbox);
                $update = "UPDATE tabel_putway SET status = '$status', refrence = '$refrence' WHERE putway_id = '$check' ";

                $query = \Yii::$app->db->createCommand($update)->execute();
            }
            if ($query) {
                $modelDo = new \common\models\MasterDo();
                $modelDo->no_do = $refrence;
                $modelDo->save();
            }
            $this->redirect(['/site/putway_confirmation']);
        }

backend/views/site/_item.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin(); ?>
<table class="table table-hover table-bordered table-striped">
	<tr>
		<td><b>Produk</b></td>
		<td><?php echo $form->field($model, 'produk')->hiddenInput([
				'value' => $model['produk'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->produk; ?>
		</td>
	</tr>
	<tr>
		<td><b>Description</b></td>
		<td><?php echo $form->field($model, 'description')->hiddenInput([
				'value' => $model['description'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->description; ?>
		</td>
	</tr>
	<tr>
		<td><b>Hu NUmber</b></td>
		<td><?php echo $form->field($model, 'hu_number')->hiddenInput([
				'value' => $model['hu_number'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->hu_number; ?>
		</td>
	</tr>
	<tr>
		<td><b>Batch Number</b></td>
		<td><?php echo $form->field($model, 'batch')->hiddenInput([
				'value' => $model['batch'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->batch; ?>
		</td>
	</tr>
	<tr>
		<td><b>Quantity</b></td>
		<td><?php echo $form->field($model, 'quantity')->hiddenInput([
				'value' => $model['quantity'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->quantity; ?>
		</td>
	</tr>
</table>
<div class="form-group">
	<?= Html::a('Send', ['/site/send', 'hu_number' => $model->hu_number], ['class' => 'btn btn-warning']); ?>
</div>
<?php ActiveForm::end(); ?>

backend/views/site/_search.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php $form = ActiveForm::begin([
	'action' => ['search'], 
	'method' => 'get',
]); ?>

<?= $form->field($model, 'hu_number')->textInput(['class' => 'form-control', 'placeholder' => 'Masukan HU Number']) ?>
<div class="form-group">
	<?= Html::submitButton('Search', ['class' => 'btn btn-primary']); ?>
</div>

<?php ActiveForm::end(); ?>

backend/views/site/_shipment.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php $form = ActiveForm::begin([
	'action' => ['shipment'], 
	'method' => 'get',
]); ?>

<?= $form->field($model, 'no_sto')->textInput(['class' => 'form-control', 'placeholder' => 'Masukan STO Number']) ?>
<div class="form-group">
	<?= Html::submitButton('Search', ['class' => 'btn btn-primary']); ?>
</div>

<?php ActiveForm::end(); ?>

backend/views/site/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\MasterData */

$this->title = Yii::t('app', ' Scanning confirmation');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Master Datas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="master-data-create">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->renderAjax('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

use kartik\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap\Progress;
/* @var $this yii\web\View */

$this->title = 'Dashboard';
?>
<div class="site-index">
    <div class="row">
        <div class="col-md-12">
            <div class="well">
                <div class="row">
                    <div class="col-md-3">
                    <h4 align="center">New</h4>
                        <?php 
                            $count = common\models\MasterData::find()->where(['status' => 'new'])->count();
                            echo "<h3 align='center'>$count</h3>";
                            echo "<p align='center'><i>pallet</i></p>";
                        ?>
                    </div>
                    <div class="col-md-3">
                        <h4 align="center">Scan</h4>
                        <?php 
                            $count = common\models\MasterData::find()->where(['status' => 'scann'])->count();
                            echo "<h3 align='center'>$count</h3>";
                            echo "<p align='center'><i>pallet</i></p>";
                        ?>
                    </div>
                    <div class="col-md-3">
                        <h4 align="center">Confirm</h4>
                        <?php 
                            $count = common\models\MasterData::find()->where(['status' => 'confirm'])->count();
                            echo "<h3 align='center'>$count</h3>";
                            echo "<p align='center'><i>pallet</i></p>";
                        ?>
                    </div>
                    <div class="col-md-3">
                        <h4 align="center">Shipment</h4>
                        <?php 
                            $count = common\models\MasterData::find()->where(['status' => 'shipment'])->count();
                            echo "<h3 align='center'>$count</h3>";
                            echo "<p align='center'><i>pallet</i></p>";
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <label>Outbound proses</label>
            <?php
                $date = date("Y-m-d");
                $new = "new";
                $done = "done";
                $countAll = \common\models\MasterData::find()
                    ->where(['LIKE', 'created_at', $date])
                    ->count();
                $countNew = \common\models\MasterData::find()
                    ->where(['status' => $new,])
                    ->andWhere(['LIKE', 'created_at', $date])
                    ->count();
                $countDone = \common\models\MasterData::find()
                    ->where(['status' => $done])
                    //->andWhere(['LIKE', 'created_at', $date])
                    ->count();
                if ($countNew != 0) {
                    $percent = round($countDone/$countAll * 100, 2);
                    // default with label
                    echo "<b>( $percent % )</b>";
                    echo Progress::widget([
                        'percent' => $percent,
                        'label' => '',
                        'barOptions' => ['class' => 'progress-bar-warning'],
                        'options' => ['class' => 'active progress-striped']
                    ]);
                } else {
                    echo Progress::widget([
                        'percent' => 0,
                        'label' => '0 %',
                        //'barOptions' => ['class' => 'progress-bar-warning'],
                        //'options' => ['class' => 'active progress-striped']
                    ]);
                }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?= \yii2fullcalendar\yii2fullcalendar::widget(array(
                        'events'=> $events,
                    )); ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <h4>Confirm status</h4>
            </div>
            <div class="form-group">
                <?= Html::beginForm(['site/index'], 'post', ['data-pjax' => '', 'class' => 'form-inline']); ?>
                <?php
                    echo yii\jui\DatePicker::widget([
                        'options' => ['class' => 'form-control'],
                        'value' => $day,
                        'name' => 'datepicker',
                        'dateFormat' => 'yyyy-MM-dd',
                        'clientOptions' =>[
                            'numberOfMonths' => 1,
                            //'minDate' => '-1m',
                            //'maxDate' => '+1m',
                            'changeMonth' => true,
                        ]
                ]) ?>
                <?= Html::submitButton('<i class="fa fa-search"></i>', ['class' => 'btn btn-primary', 'name' => 'hash-button']) ?>
                <?= Html::endForm() ?>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php 

                    $gridColumns = [
                        [
                            'class' => '\kartik\grid\SerialColumn'
                        ],
                        'type_produk',
                        'batch',
                        'hu_number',
                        'quantity',
                        [
                            'attribute' => 'status',
                            'format' => 'raw',
                            'value' => function ($model) {
                                if ($model->status == 'confirm') {
                                    return "<i class='fa fa-check' style='color:green;'></i>";
                                }
                            },
                        ],
                    ];
                    echo GridView::widget([
                        'dataProvider'  => $dataProviderFg,
                        'columns'       => $gridColumns,
                        'responsive'    =>true,
                        'hover'         =>true,
                        'pjax'          =>true,
                        'striped'       => true,
                        'pjaxSettings'  =>[
                            'neverTimeout' => true,
                        ],
                        'floatHeader'=>false,
                        'floatHeaderOptions'=>['scrollingTop'=>'50'],
                    ]);
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Golden</b>App</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Sign in', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>
        <?php ActiveForm::end(); ?>
    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

backend/views/site/outbound.php
<?php 

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\grid\GridView;

$this->title = Yii::t('app', 'Outbound Finish Good');
$this->params['breadcrumbs'][] = $this->title;

?>
<h1><?= \yii\helpers\Html::encode($this->title); ?></h1>
<?= Html::beginForm(['site/outbound'], 'post'); ?>
	<?php 
	$gridColumns = [
	    [
	        'class' => '\kartik\grid\SerialColumn'
	    ],
	    [
	        'class'       => '\kartik\grid\CheckboxColumn',
	        'pageSummary' => true,
	        'rowSelectedClass' => GridView::TYPE_DANGER	,
	    ],
	    'produk',
	    'hu_number', 
	    'batch', 
	    'quantity',
	    'no_sto',
	    'driver_name',
	    'no_pol'
    ];
	echo GridView::widget([
	    'dataProvider' 	=> $dataProvider,
	    //'filterModel'  	=> $searchModel,
	    'columns'      	=> $gridColumns,
	    'responsive'   	=>true,
	    'hover'        	=>true,
	    'pjax'         	=>true,
	    'striped'		=> true,
	    'pjaxSettings' 	=>[
	        'neverTimeout' => true,
	//      'beforeGrid'   => 'My fancy content before.',
	//      'afterGrid'    => 'My fancy content after.',
	    ],
	    'floatHeader'=>false,
	    'floatHeaderOptions'=>['scrollingTop'=>'50'],
	//  'showPageSummary' => true,
	]); 
?>
<?= Html::submitButton('Confirm', [ 'id' => 'update', 'class' => 'btn btn-success']) ?>
<?= Html::endForm(); ?>

backend/views/site/pdfreport.php
<p style="margin-left: 7cm;">PT. KAMADJAJA LOGISTICS</p>
<p style="margin-left: 7.6cm;"><b>DELIVERY ORDER</b></p>
<table style="width: 100%";>
	<tr>
		<td>STO Number</td>
		<td>:</td>
		<td><h5><b><?php echo $no_sto; ?></b></h5></td>
		<td>Delivery Date</td>
		<td>:</td>
		<td><?php echo date("d/m/Y"); ?></td>
	</tr>
	<tr>
		<td>Truck No</td>
		<td>:</td>
		<td><?php echo $no_pol; ?></td>
		<td>Driver Name</td>
		<td>:</td>
		<td><?php echo $nama_supir; ?></td>
	</tr>
	<tr>
		<td>Type truck</td>
		<td>:</td>
		<td><?php echo $jenis_truk; ?></td>
		<td>Transporter</td>
		<td>:</td>
		<td><?php echo $transporter; ?></td>
	</tr>
</table>
<br>
<table>
	<tr>
		<td><b>On Behalf of :<b></td>
		<td><b>Delivered To :</b></td>
	</tr>
	<tr>
		<td>PT. Kamadjaja Logistics,
			Jln Kiwi, Pergudangan Karplindo
			Ciracas, Jakarta Timur
		</td>
		<td><?php echo $address; ?></td>
	</tr>
</table>
<br><br>
<table style="border-collapse: collapse; width: 100%;">
	<tr style="background-color: #F2F2F2;">
		<th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">No</th>
		<th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">Produk</th>
		<th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">Description</th>
		<th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">Batch Number</th>
		<th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">HU Number</th>
		<th style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;">Quantity</th>
	</tr>
	<tbody>
		<?php 
		$no = 1;
		foreach ($models as $model) { ?>
		<tr>
			<td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;"><?php echo $no; ?></td>
			<td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;"><?php echo $model->produk; ?></td>
			<td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;"><?php echo $model->description; ?></td>
			<td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;"><?php echo $model->batch; ?></td>
			<td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;"><?php echo $model->hu_number; ?></td>
			<td style="padding: 8px; text-align: left; border-bottom: 1px solid #ddd;"><?php echo $model->quantity; ?></td>
		</tr>
		<?php $no++; } ?>
	</tbody>
</table>
<br>
<table style="width: 100%;">
	<tr>
		<td>Masuk :</td>
		<td>Start :</td>
		<td>Finish :</td>
		<td>Keluar :</td>
	</tr>
</table>
<table style="border-collapse: collapse; width: 100%; margin-top: 5cm;">
	<tr>
		<td style=" height: 1cm; width: 30%;"><b>Admin Warehouse :</b></td>
		<td style=" height: 1cm; width: 30%;"><b>Driver Name :</b> <?php echo $nama_supir; ?></td>
		<td style=" height: 1cm; width: 30%;"><b>Spv/Asst. Mgr :</b> Restu / Eddy</td>
	</tr>
</table>

backend/views/site/search.php
<?php 

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

$this->title = Yii::t('app', 'Search');
$this->params['breadcrumbs'][] = $this->title;

?>
<h1><?= \yii\helpers\Html::encode($this->title); ?></h1>
<?php echo $this->render('_search', ['model' => $searchModel]); ?>
<?php 
	if($searchModel->hu_number != null){
		echo GridView::widget([
					'dataProvider' => $dataProvider,
					// 'filterModel' => $searchModel,
					'columns' => [
						[						
							'class' => 'yii\grid\ActionColumn',
							'header' => 'Actions',
							'buttons' => [
								'checkin' => function ($url,$model) {
									return Html::a(
										'<span class="fa fa-check-circle"></span>',
										//without delete action
										//['/checkin/checkin_security','transporter'=>$model->no_truck],
										//---------------------
										['/site/send','hu_number'=>$model->hu_number],
										[
											'title' => 'Check-IN',
										]
									);
								},
							],
							'template' => '{checkin}',
						],
							'produk',
							'description',
							'quantity',
					],
				]);	
	}
	else{
		Yii::$app->session->setFlash('warning', 'Please Masukan HU Number');
	}
?>

backend/views/site/sukses.php
<?php 

use yii\helpers\Html;

$this->title = Yii::t('app', 'Sukses Konfirmasi');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="well">
	<h4>Order Number : <?php echo $code; ?></h4>
</div>

backend/views/site/tree.php
<?php

use execut\widget\TreeView;
use yii\web\JsExpression;

$data = [
    [
        'text' => 'Parent 1',
        'nodes' => [
            [
                'text' => 'Child 1',
                'nodes' => [
                    [
                        'text' => 'Grandchild 1'
                    ],
                    [
                        'text' => 'Grandchild 2'
                    ]
                ]
            ],
            [
                'text' => 'Child 2',
            ]
        ],
    ],
    [
        'text' => 'Parent 2',
        'nodes' => [
            [
                'text' => 'Child 1',
                'nodes' => [
                    [
                        'text' => 'Grandchild 1'
                    ],
                    [
                        'text' => 'Grandchild 2'
                    ]
                ]
            ],
            [
                'text' => 'Child 2',
            ]
        ],
    ]
];

$onSelect = new JsExpression(<<<JS
function (undefined, item) {
    console.log(item);
}
JS
);
$groupsContent = TreeView::widget([
    'data' => $data,
    'size' => TreeView::TEMPLATE_ADVANCED,
    'header' => 'Categories',
    'searchOptions' => [
      'inputOptions' => [
            'placeholder' => 'Search category...'
        ],
    ],
    'clientOptions' => [
        'onNodeSelected' => $onSelect,
        'selectedBackColor' => 'rgb(40, 153, 57)',
        'borderColor' => '#fff',
    ],
]);

echo $groupsContent;